---
title: "Lab 6"
author:
- "Austin Collins"
- "Ian Cornish"
- "Taylor Rouse"
- "Omar Taylor"
date: "April 12, 2018"
output: html_document
---

## GitHub Repository
https://github.com/icornish97/Lab6

# Dataset Overview
We have chosen to continue working with the Behavioral Risk Factor Surveillance System (BRFSS) dataset. The difference this time is that we are analyzing specific variables from the data for all 50 states instead of just for Iowa, as we did during our midterm exam. Additionally, we plan to merge the dataset from a variable amount of years in order to analyze how time has had an effect on the results. As you know, this dataset is an aggregation of the responses from surveys collected from all 50 states about the health-related risk behaviors, chronic health conditions, and use of preventive services from U.S. residents.

# Cleaning Steps
Since we are working with a multi-year dataset, with the data from each year having their own respective files, joining the data will be part of the challenge. Since we have selected a finite amount of variables to analyze for teh dataset, we will have to work to condense the data to only include such columns. All further cleaning will depend on what analyses we are trying to conduct as we work through our data, such as separating the data into key value pairs if necessary, refactoring variables, changing types, etc. We have already gotten started with the cleaning process, which can be viewed below

## Code Thus Far

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
install.packages("SASxport", repos = "http://cran.us.r-project.org")
library(SASxport)


```

### Marginal Distributions/Densities


```{R, cache = TRUE}
zipfile <- "./dataset/2016/LLCP2016XPT.zip"
outDir <- "./dataset/2016"
unzip(zipfile, exdir = outDir)
data <- read.xport("dataset/2016/LLCP2016.XPT")
```

## Variables From Dataset

These are the list of variables we have selected to analyze from the large dataset.

-AVEDRNK2
-SEX
-MENTHLTH
-GENHTLH
-DRNK3GE5
-SMOKDAY2
-INCOME2
-MARITAL

How many days on average with poor mental health did people who drink alot have versus people that do
not drink alot.
MENTHLTH, DRNK3GE5 (Over 10) 

```{R}
heavyDrinkers <- data %>% filter(DRNK3GE5>= 10 & DRNK3GE5 < 76) %>% filter (MENTHLTH <= 30 | MENTHLTH == 88) %>% select(MENTHLTH) 
heavyDrinkers$status <- "Heavy"
lightDrinkers <- data %>% filter(DRNK3GE5<10 & DRNK3GE5 < 76 ) %>% filter(MENTHLTH<=30 | MENTHLTH == 88) %>% select(MENTHLTH)
lightDrinkers$status <- "Light"
tmp <- rbind(heavyDrinkers, lightDrinkers)
tmp$MENTHLTH[tmp$MENTHLTH == 88] <- 0
drinkData <- tmp
drinkData %>% group_by(status) %>% summarise(avgMentalHealth = mean(MENTHLTH)) %>% ggplot(aes (x= status, y=avgMentalHealth))+ geom_col() + labs(x= "Drinking Status", y = "Average days (in the last 30) with bad mental health")
```


What is the general health of people that drink alot versus people that do
not drink alot.
GENHLTH, DRNK3GE5 (Over 10) 
```{R}
data %>% filter(DRNK3GE5>= 10 & DRNK3GE5 < 76) %>% filter(GENHLTH != 7 & GENHLTH != 9) %>% select(GENHLTH)
heavyDrinkersGen <- data %>% filter(DRNK3GE5>= 10 & DRNK3GE5 < 76) %>% filter(GENHLTH != 7 & GENHLTH != 9) %>% select(GENHLTH) 
heavyDrinkersGen$status <- "Heavy"
lightDrinkersGen <- data %>% filter(DRNK3GE5<10 & DRNK3GE5 < 76 ) %>% filter(GENHLTH != 7 & GENHLTH != 9) %>% select(GENHLTH)
lightDrinkersGen$status <- "Light"

heavyDrinkersGen$GENHLTH[heavyDrinkersGen$GENHLTH == 1] <- "Excellent"
heavyDrinkersGen$GENHLTH[heavyDrinkersGen$GENHLTH == 2] <- "Very Good"
heavyDrinkersGen$GENHLTH[heavyDrinkersGen$GENHLTH == 3] <- "Good"
heavyDrinkersGen$GENHLTH[heavyDrinkersGen$GENHLTH == 4] <- "Fair"
heavyDrinkersGen$GENHLTH[heavyDrinkersGen$GENHLTH == 5] <- "Poor"

lightDrinkersGen$GENHLTH[lightDrinkersGen$GENHLTH == 1] <- "Excellent"
lightDrinkersGen$GENHLTH[lightDrinkersGen$GENHLTH == 2] <- "Very Good"
lightDrinkersGen$GENHLTH[lightDrinkersGen$GENHLTH == 3] <- "Good"
lightDrinkersGen$GENHLTH[lightDrinkersGen$GENHLTH == 4] <- "Fair"
lightDrinkersGen$GENHLTH[lightDrinkersGen$GENHLTH == 5] <- "Poor"

heavyDrinkersGen$GENHLTH <- factor(heavyDrinkersGen$GENHLTH, levels= c("Excellent", "Very Good", "Good", "Fair", "Poor"))
lightDrinkersGen$GENHLTH <- factor(lightDrinkersGen$GENHLTH, levels= c("Excellent", "Very Good", "Good", "Fair", "Poor"))
lightDrinkersGen %>% ggplot(aes(x=GENHLTH))+geom_bar()+ggtitle("General health breakdown of light drinkers")
lightDrinkersGen %>% group_by(GENHLTH) %>% summarise(numberOfRespondents = n())
heavyDrinkersGen %>% ggplot(aes(x=GENHLTH))+geom_bar()+ggtitle("General health breakdown of heavy drinkers")
heavyDrinkersGen %>% group_by(GENHLTH) %>% summarise(numberOfRespondents = n())
```

How many days on average with poor mental health did people who smoke alot have versus people that do not smoke a lot or not at all?

```
heavySmokers <- data %>% filter(SMOKDAY2==1) %>% filter (MENTHLTH <= 30 | MENTHLTH == 88) %>% select(MENTHLTH) 
heavySmokers$status <- "Heavy Smocker"
moderateSmokers <- data %>% filter(SMOKDAY2==2) %>% filter(MENTHLTH<=30 | MENTHLTH == 88) %>% select(MENTHLTH)
moderateSmokers$status <- "Moderate Smoker"
nonSmokers <- data %>% filter(SMOKDAY2==3) %>% filter (MENTHLTH <= 30 | MENTHLTH == 88) %>% select(MENTHLTH) 
nonSmokers$status <- "Non Smoker"
tmp2 <- rbind(heavySmokers, moderateSmokers, nonSmokers)
tmp2$MENTHLTH[tmp2$MENTHLTH == 88] <- 0
smokerData <- tmp2
smokerData %>% group_by(status) %>% summarise(avgMentalHealth = mean(MENTHLTH))
smokerData %>% group_by(status) %>% summarise(avgMentalHealth = mean(MENTHLTH)) %>% 
  ggplot(aes (x= status, y=avgMentalHealth))+ 
  geom_col() + labs(x= "Smoking Status",
                    y = "Average days (in the last 30) with bad mental health")
```
What is the general health of people that smoke alot versus people that do not smoke alot or not at all.

```
heavySmokersGen<- data %>% filter(SMOKDAY2==1) %>% filter (GENHLTH <= 5) %>% select(GENHLTH) 
heavySmokersGen$status <- "Heavy Smocker"
moderateSmokersGen <- data %>% filter(SMOKDAY2==2) %>% filter(GENHLTH <= 5) %>% select(GENHLTH)
moderateSmokersGen$status <- "Moderate Smoker"
nonSmokersGen<- data %>% filter(SMOKDAY2==3) %>% filter (GENHLTH <= 5) %>% select(GENHLTH) 
nonSmokersGen$status <- "Non Smoker"

heavySmokersGen$GENHLTH[heavySmokersGen$GENHLTH == 1] <- "Excellent"
heavySmokersGen$GENHLTH[heavySmokersGen$GENHLTH == 2] <- "Very Good"
heavySmokersGen$GENHLTH[heavySmokersGen$GENHLTH == 3] <- "Good"
heavySmokersGen$GENHLTH[heavySmokersGen$GENHLTH == 4] <- "Fair"
heavySmokersGen$GENHLTH[heavySmokersGen$GENHLTH == 5] <- "Poor"

moderateSmokersGen$GENHLTH[moderateSmokersGen$GENHLTH == 1] <- "Excellent"
moderateSmokersGen$GENHLTH[moderateSmokersGen$GENHLTH == 2] <- "Very Good"
moderateSmokersGen$GENHLTH[moderateSmokersGen$GENHLTH == 3] <- "Good"
moderateSmokersGen$GENHLTH[moderateSmokersGen$GENHLTH == 4] <- "Fair"
moderateSmokersGen$GENHLTH[moderateSmokersGen$GENHLTH == 5] <- "Poor"

nonSmokersGen$GENHLTH[nonSmokersGen$GENHLTH == 1] <- "Excellent"
nonSmokersGen$GENHLTH[nonSmokersGen$GENHLTH == 2] <- "Very Good"
nonSmokersGen$GENHLTH[nonSmokersGen$GENHLTH == 3] <- "Good"
nonSmokersGen$GENHLTH[nonSmokersGen$GENHLTH == 4] <- "Fair"
nonSmokersGen$GENHLTH[nonSmokersGen$GENHLTH == 5] <- "Poor"

heavySmokersGen$GENHLTH <- factor(heavySmokersGen$GENHLTH, levels= c("Excellent", "Very Good", "Good", "Fair", "Poor"))
moderateSmokersGen$GENHLTH <- factor(moderateSmokersGen$GENHLTH, levels= c("Excellent", "Very Good", "Good", "Fair", "Poor"))
nonSmokersGen$GENHLTH <- factor(nonSmokersGen$GENHLTH, levels= c("Excellent", "Very Good", "Good", "Fair", "Poor"))

heavySmokersGen %>% ggplot(aes(x=GENHLTH))+geom_bar()+ggtitle("General health breakdown of heavy smokers")
moderateSmokersGen %>% ggplot(aes(x=GENHLTH))+geom_bar()+ggtitle("General health breakdown of moderate smokers")
nonSmokersGen %>% ggplot(aes(x=GENHLTH))+geom_bar()+ggtitle("General health breakdown of nonsmokers")

tmp <- rbind(heavySmokersGen, moderateSmokersGen, nonSmokersGen)
tmp %>% ggplot(aes(x = GENHLTH, fill=status)) + geom_bar(position="fill")
```
